<?xml version="1.0"?>
<package format="3">
  <name>arms_video</name>
  <version>0.1.0</version>
  <description>Launch file for usb_cam (FPV video capture).</description>
  <maintainer email="dev@arms.local">arms</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>usb_cam</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
